/* Home, persistent intake, and the existing Cell 5 explorer share one workspace. */
const $=id=>document.getElementById(id);
let snapshot=null,revision=-1,dataRevision=-1,lastProject=null,route='home',selectedEntry=null,detailTab='report',renderKey='',refreshing=false,toastTimer=null;
window.nzApi=async(method,args={},read=false)=>{const response=await fetch('/api/'+method,{signal:AbortSignal.timeout(15000),method:read?'GET':'POST',headers:{Authorization:'Bearer '+NOZEOMICS.token,'Content-Type':'application/json'},body:read?undefined:JSON.stringify(args)});const value=await response.json();if(!response.ok){const e=new Error(value.error?.message||'Request failed');e.code=value.error?.code;throw e;}return value;};
function node(tag,cls,text){const e=document.createElement(tag);if(cls)e.className=cls;if(text!==undefined)e.textContent=text;return e;}
function instantButton(text,fn,cls=''){const b=node('button',cls,text);b.type='button';b.onclick=fn;return b;}
function entryLabel(e){return e.display_label||e.gse;}
function groupCounts(e){return 'Control '+Object.values(e.groups).filter(g=>g==='Group A').length+', Treated '+Object.values(e.groups).filter(g=>g==='Group B').length;}
function toast(text){clearTimeout(toastTimer);$('toast').textContent=text;$('toast').hidden=false;toastTimer=setTimeout(()=>$('toast').hidden=true,3500);}
function button(text,fn,cls=''){const b=node('button',cls,text);b.type='button';b.onclick=async()=>{b.disabled=true;try{await fn();}catch(e){toast(e.message);}finally{b.disabled=false;}};return b;}
const stateNames={intake:'In preparation',processing:'Preparing analysis',analysis:'Analysis ready',fetching:'Reading GEO metadata',awaiting_review:'Waiting for AI review',approved:'AI review passed',returned:'Needs attention'};
function badge(status){return node('span','badge '+status,stateNames[status]||status);}
async function mutation(method,args){for(let attempt=0;attempt<3;attempt++){const fresh=await nzApi('state',{},true);if(args.project_id&&method!=='open_project'&&fresh.active_project!==args.project_id)throw new Error('This project is no longer open.');try{return await nzApi(method,{...args,base_revision:fresh.revision});}catch(e){if(e.code!=='revision_conflict'||attempt===2)throw e;}}}
function showScreen(name){$('graph-controls').hidden=name!=='analysis'||!['trend','ma','heatmap','pca'].includes($('graph-controls').dataset.graph);$('new').hidden=name!=='home';for(const id of ['home','intake','analysis'])$(id).hidden=id!==name;$('back-home').hidden=name==='home';$('project-title').textContent=name==='home'?'':snapshot?.project?.name||'';}
function renderHome(){const list=$('project-list');list.replaceChildren();for(const p of snapshot.projects){const card=button('',async()=>{await mutation('open_project',{project_id:p.id});route='project';selectedEntry=null;renderKey='';await refresh(true);},'project-card');card.append(node('strong','',p.name),badge(p.stage),node('span','card-meta',[p.organism==='Homo sapiens'?'Human':p.organism==='Mus musculus'?'Mouse':null,p.gse_count+' GSE'+(p.gse_count===1?'':'s'),p.comparisons+' comparison'+(p.comparisons===1?'':'s')].filter(Boolean).join(' · ')));list.append(card);}if(!snapshot.projects.length){const empty=node('div','empty-state'),img=node('img');img.src='/assets/Omics.png';empty.append(img,node('h2','','Start your first study'),node('p','','Create a project to bring GEO datasets together.'));list.append(empty);}}
async function newProject(){const box=node('div'),input=node('input'),label=node('label','','Project name');input.type='text';input.value='Untitled project';input.setAttribute('aria-label','Project name');const actions=node('div','actions');actions.append(button('Create project',async()=>{await mutation('open_project',{name:input.value.trim()||'Untitled project',workflow:'intake'});$('modal').close();route='project';selectedEntry=null;detailTab='report';renderKey='';await refresh(true);},'primary'));box.append(node('h2','','New project'),label,input,actions);$('modal-body').replaceChildren(box);$('modal').showModal();input.focus();input.select();input.onkeydown=e=>{if(e.key==='Enter'){e.preventDefault();actions.querySelector('button').click();}};}
$('new').onclick=newProject;
$('gse-form').onsubmit=async e=>{e.preventDefault();const accessions=$('gse-input').value.toUpperCase().split(/[\s,;]+/).filter(Boolean);if(!accessions.length)return;const b=$('add-gses');b.disabled=true;try{const answer=await mutation('add_gses',{accessions,project_id:snapshot.project.id});if(answer.entry_ids.length)selectedEntry=answer.entry_ids[0];else toast('These GSEs are already in this project.');$('gse-input').value='';await refresh();}catch(error){toast(error.message);}finally{b.disabled=false;}};
function activeEntries(){const entries=Object.values(snapshot?.project?.intake||{}).filter(e=>e.status!=='excluded'),order=snapshot?.project?.intake_order||[];return entries.sort((a,b)=>{const ai=order.indexOf(a.id),bi=order.indexOf(b.id);return (ai<0?order.length:ai)-(bi<0?order.length:bi);});}
let draggingGse=null,gseDrag=null,suppressGseClick=false;
function renderIntake(){
 const entries=activeEntries(),list=$('gse-list');if(!entries.some(e=>e.id===selectedEntry))selectedEntry=entries[0]?.id;list.replaceChildren();
 const processing=snapshot.project.stage==='processing';
 for(const e of entries){
  const card=node('div','gse-card'+(selectedEntry===e.id?' active':''));card.draggable=false;card.dataset.entry=e.id;
  const main=instantButton('',()=>{if(suppressGseClick){suppressGseClick=false;return;}if(selectedEntry===e.id)detailTab={report:'groups',groups:'files',files:'report'}[detailTab];else selectedEntry=e.id;renderIntake();},'gse-card-main');
  const line=node('div','gse-card-line');line.append(node('strong','',entryLabel(e)),node('span','gse-counts',groupCounts(e)));main.append(line,node('span','gse-title',e.report?.title?.join(' ')||''));card.append(main);
  function showGseDetails(){hideSampleTooltip();sampleTooltip=node('div','sample-tooltip gse-tooltip');sampleTooltip.setAttribute('role','tooltip');const headline=node('div','gse-tooltip-head');headline.append(node('span','gse-tooltip-code',entryLabel(e)),node('span','gse-tooltip-counts',groupCounts(e)));sampleTooltip.append(headline,node('div','gse-tooltip-title',e.report?.title?.join(' ')||''));document.body.append(sampleTooltip);const rect=main.getBoundingClientRect();sampleTooltip.style.left=Math.max(12,Math.min(rect.right+10,innerWidth-sampleTooltip.offsetWidth-12))+'px';sampleTooltip.style.top=Math.max(12,Math.min(rect.top,innerHeight-sampleTooltip.offsetHeight-12))+'px';}
  main.onmouseenter=showGseDetails;main.onmouseleave=hideSampleTooltip;main.onfocus=showGseDetails;main.onblur=hideSampleTooltip;

  const remove=button('×',()=>confirmRemove(e),'gse-remove');remove.setAttribute('aria-label','Remove '+entryLabel(e));remove.disabled=processing;card.append(remove);
  const tabs=node('div','gse-bookmarks');for(const [key,label] of [['report','Report'],['groups','Group'],['files','Files']]){const tab=instantButton(label,()=>{selectedEntry=e.id;detailTab=key;renderIntake();},selectedEntry===e.id&&detailTab===key?'active':'');tab.setAttribute('aria-pressed',String(selectedEntry===e.id&&detailTab===key));tabs.append(tab);}card.append(tabs);
  main.onpointerdown=event=>{if(event.button!==0||processing)return;gseDrag={id:e.id,startX:event.clientX,startY:event.clientY,active:false,pointerId:event.pointerId,main,card};main.setPointerCapture(event.pointerId);};
  main.onpointermove=event=>{if(!gseDrag||gseDrag.id!==e.id)return;if(!gseDrag.active&&Math.hypot(event.clientX-gseDrag.startX,event.clientY-gseDrag.startY)<6)return;gseDrag.active=true;draggingGse=e.id;hideSampleTooltip();card.classList.add('dragging');const target=document.elementFromPoint(event.clientX,event.clientY)?.closest('.gse-card');if(target&&target!==card&&target.parentNode===list){const bounds=target.getBoundingClientRect();list.insertBefore(card,event.clientY<bounds.top+bounds.height/2?target:target.nextSibling);}const bounds=list.getBoundingClientRect();if(event.clientY<bounds.top+30)list.scrollTop-=12;else if(event.clientY>bounds.bottom-30)list.scrollTop+=12;};
  main.onpointerup=async event=>{if(!gseDrag||gseDrag.id!==e.id)return;const moved=gseDrag.active;gseDrag=null;draggingGse=null;if(main.hasPointerCapture(event.pointerId))main.releasePointerCapture(event.pointerId);card.classList.remove('dragging');if(!moved)return;suppressGseClick=true;setTimeout(()=>{suppressGseClick=false;},0);const order=[...list.querySelectorAll('.gse-card')].map(item=>item.dataset.entry);try{await mutation('update_intake',{entry_id:e.id,action:'reorder',order,project_id:snapshot.project.id});await refresh(true);}catch(error){toast(error.message);await refresh(true);}};
  main.onpointercancel=()=>{gseDrag=null;draggingGse=null;card.classList.remove('dragging');renderIntake();};
  list.append(card);
 }
 $('add-gses').disabled=processing;$('gse-input').disabled=processing;
 $('intake-complete').textContent=entries.length+' GSE'+(entries.length===1?'':'s')+' · Complete';$('intake-complete').disabled=!entries.length||processing||entries.some(e=>e.status==='fetching');
 renderDetail(entries.find(e=>e.id===selectedEntry));
}
function confirmRemove(e){const box=node('div'),actions=node('div','actions');box.append(node('h2','','Remove '+entryLabel(e)+'?'));actions.append(button('Cancel',()=>$('modal').close()),button('Remove',async()=>{await groupQueue;await mutation('update_intake',{entry_id:e.id,action:'exclude',project_id:snapshot.project.id});$('modal').close();await refresh(true);},'primary'));box.append(actions);$('modal-body').replaceChildren(box);$('modal').showModal();}
$('intake-complete').onclick=async()=>{await groupQueue;const box=node('div'),actions=node('div','actions');box.append(node('h2','','Confirm grouping'));for(const e of activeEntries())box.append(node('p','',entryLabel(e)+' · '+groupCounts(e)));box.append(node('p','muted','Ask your connected AI to review this batch.'));actions.append(button('OK',()=>$('modal').close(),'primary'));box.append(actions);$('modal-body').replaceChildren(box);$('modal').showModal();};
function renderDetail(e){hideSampleTooltip();const detail=$('gse-detail');detail.replaceChildren();if(!e){const empty=node('div','empty-state');detail.append(empty);return;}const body=node('div','detail-body');detail.append(body);
 if(e.reason)body.append(node('div','notice error',e.reason));if(e.notice)body.append(node('div','notice',e.notice));
 if(detailTab==='report'){if(!Object.keys(e.report||{}).length){body.append(node('p','muted',e.phase));return;}for(const [key,label]of [['title','Study'],['summary','Summary'],['overall_design','Design'],['type','Experiment']]){if(e.report[key]?.length)body.append(node('h3','',label),node('p','',e.report[key].join('\n')));}if(e.review?.source_limitations)body.append(node('div','notice',e.review.source_limitations));for(const d of snapshot.project.datasets.filter(d=>e.dataset_ids.includes(d.id))){body.append(node('h3','',d.data_type_label||d.unit),node('p','muted',d.rows.toLocaleString()+' genes · '+d.columns+' samples'));if(d.partial_results)body.append(node('div','notice','Only the submitted subset of genes is available.'));}}
 if(detailTab==='groups')renderGroups(body,e);
 if(detailTab==='files'){if(!e.files.length)body.append(node('p','muted',e.status==='fetching'?'Reading file list…':'No supplementary files listed.'));const table=node('table'),thead=node('thead'),tr=node('tr');['Source file','Size','Status'].forEach(t=>tr.append(node('th','',t)));thead.append(tr);table.append(thead);const tbody=node('tbody');for(const f of e.files){const row=node('tr'),name=node('td','file-name',f.name);if(f.error)name.append(node('span','sample-description',f.error));row.append(name,node('td','file-size',f.bytes?formatBytes(f.bytes):'—'),node('td','',({not_downloaded:'Not downloaded',pending:'Not downloaded',queued:'Selected by AI',downloading:'Downloading selected file',downloaded:'Cached',failed:'Download failed'})[f.status]||f.status));tbody.append(row);}table.append(tbody);body.append(table);}}
function formatBytes(n){return n>=1024**3?(n/1024**3).toFixed(1)+' GB':n>=1024**2?(n/1024**2).toFixed(1)+' MB':n>=1024?(n/1024).toFixed(1)+' KB':n+' B';}
let groupQueue=Promise.resolve(),pendingGroupWrites=0;
function saveGroups(e,groups){const pid=snapshot.project.id;pendingGroupWrites++;groupQueue=groupQueue.then(async()=>{try{await mutation('update_intake',{entry_id:e.id,groups,project_id:pid});}catch(error){toast(error.message);}finally{pendingGroupWrites--;if(!pendingGroupWrites)await refresh(false,true);}});}
const groupViews=new Map();let resizingGroups=false;
let sampleTooltip=null;
function positionSampleTooltip(event,row){if(!sampleTooltip)return;const rect=row.getBoundingClientRect(),x=Number.isFinite(event?.clientX)?event.clientX:rect.right,y=Number.isFinite(event?.clientY)?event.clientY:rect.bottom;const width=sampleTooltip.offsetWidth,height=sampleTooltip.offsetHeight;sampleTooltip.style.left=Math.max(12,x+16+width<=innerWidth-12?x+16:x-width-16)+'px';sampleTooltip.style.top=Math.max(12,Math.min(y+16,innerHeight-height-12))+'px';}
function hideSampleTooltip(){sampleTooltip?.remove();sampleTooltip=null;}
function sampleTreatment(sample){
 const values=(sample.characteristics||[]).flatMap(value=>{const match=String(value).match(/^\s*(?:treatment(?:[ _-](?:group|condition))?|drug(?:[ _-]treatment)?|compound)\s*:\s*(.+)$/i);return match?[match[1].trim()]:[];});
 return [...new Set(values)].join(' · ')||'Not specified';
}
function renderGroups(body,e){
 hideSampleTooltip();if(!e.samples.length){body.append(node('p','muted',e.status==='fetching'?'Reading sample information…':'No sample information.'));return;}
 const view=groupViews.get(e.id)||{treatment:'',ratio:1/3};groupViews.set(e.id,view);const disabled=snapshot.project.stage==='processing';
 const layout=node('div','sample-picker compact-picker'),included=node('section','included-section'),heading=node('div','picker-heading');
 const chosen=e.samples.filter(s=>['Group A','Group B'].includes(e.groups[s.gsm]));heading.append(node('h3','','Included list'),node('span','muted',chosen.length+' samples'));included.append(heading);
 const top=node('div','sample-items');for(const sample of chosen)top.append(sampleRow(sample,true));if(!chosen.length)top.append(node('div','picker-empty','No samples'));top.scrollTop=view.includedScroll||0;top.onscroll=()=>{view.includedScroll=top.scrollTop;};included.append(top);layout.append(included);
 const available=node('section','available-section'),controls=node('div','picker-heading'),filter=node('select');filter.setAttribute('aria-label','Filter by treatment');
 const options=['',...new Set(e.samples.map(sampleTreatment))];if(!options.includes(view.treatment))view.treatment='';for(const value of options){const option=node('option','',value||'All treatments');option.value=value;filter.append(option);}filter.value=view.treatment;filter.onchange=()=>{view.treatment=filter.value;redraw();};
 const availableSamples=e.samples.filter(s=>!['Group A','Group B'].includes(e.groups[s.gsm]));const samples=availableSamples.filter(s=>!view.treatment||sampleTreatment(s)===view.treatment);controls.append(node('h3','','Available list'),node('span','muted',samples.length+' / '+availableSamples.length+' samples'),filter);available.append(controls);
 const bottom=node('div','sample-items');for(const sample of samples)bottom.append(sampleRow(sample,false));if(!samples.length)bottom.append(node('div','picker-empty','No matching samples'));available.append(bottom);const divider=node('div','group-divider');divider.tabIndex=0;divider.setAttribute('role','separator');divider.setAttribute('aria-label','Resize sample lists');divider.setAttribute('aria-orientation','horizontal');
 function setRatio(value){view.ratio=Math.max(.15,Math.min(.8,value));layout.style.setProperty('--included-ratio',view.ratio);divider.setAttribute('aria-valuenow',Math.round(view.ratio*100));}
 setRatio(view.ratio??1/3);divider.setAttribute('aria-valuemin','15');divider.setAttribute('aria-valuemax','80');
 divider.onpointerdown=event=>{if(event.button!==0)return;event.preventDefault();hideSampleTooltip();resizingGroups=true;divider.setPointerCapture(event.pointerId);};
 divider.onpointermove=event=>{if(!resizingGroups||!divider.hasPointerCapture(event.pointerId))return;const bounds=layout.getBoundingClientRect();setRatio((event.clientY-bounds.top)/bounds.height);};
 const finishResize=event=>{if(divider.hasPointerCapture(event.pointerId))divider.releasePointerCapture(event.pointerId);resizingGroups=false;};divider.onpointerup=finishResize;divider.onpointercancel=finishResize;
 divider.onkeydown=event=>{if(['ArrowUp','ArrowDown','Home'].includes(event.key)){event.preventDefault();setRatio(event.key==='Home'?1/3:view.ratio+(event.key==='ArrowUp'?-.025:.025));}};
 layout.append(divider,available);body.append(layout);top.scrollTop=view.includedScroll||0;bottom.scrollTop=view.availableScroll||0;bottom.onscroll=()=>{view.availableScroll=bottom.scrollTop;};
 function redraw(){view.includedScroll=top.scrollTop;view.availableScroll=bottom.scrollTop;body.replaceChildren();renderGroups(body,e);}
 function assign(sample,target,row){hideSampleTooltip();const old=e.groups[sample.gsm];e.groups[sample.gsm]=target;saveGroups(e,{[sample.gsm]:target});if(old!=='N/A'&&target!=='N/A'&&row){const toggle=row.querySelector('.sample-group-toggle');toggle.textContent=target==='Group A'?'Control':'Treated';toggle.className='sample-group-toggle '+(target==='Group A'?'control':'treated');toggle.setAttribute('aria-label',sample.gsm+' switch to '+(target==='Group A'?'Group B':'Group A'));}else redraw();const card=document.querySelector('[data-entry="'+e.id+'"] .gse-counts');if(card)card.textContent=groupCounts(e);}
 function sampleRow(sample,isIncluded){
  const row=node('div','compact-sample');if(isIncluded){const target=e.groups[sample.gsm]==='Group A'?'Group B':'Group A',toggle=instantButton(e.groups[sample.gsm]==='Group A'?'Control':'Treated',()=>assign(sample,e.groups[sample.gsm]==='Group A'?'Group B':'Group A',row),'sample-group-toggle '+(e.groups[sample.gsm]==='Group B'?'treated':'control'));toggle.disabled=disabled;toggle.setAttribute('aria-label',sample.gsm+' switch to '+target);row.append(toggle);}
  const item=instantButton('',()=>assign(sample,isIncluded?'N/A':'Group A',row),'sample-item');item.disabled=disabled;item.append(node('span','sample-gsm',sample.gsm),node('span','sample-name',sample.name||sample.gsm));item.setAttribute('aria-label',sample.gsm+' '+(isIncluded?'remove from included list':'add to included list'));row.append(item);
  if(!isIncluded)row.oncontextmenu=event=>{event.preventDefault();if(!disabled)assign(sample,'Group B',row);};
  function show(event){hideSampleTooltip();sampleTooltip=node('div','sample-tooltip');sampleTooltip.setAttribute('role','tooltip');sampleTooltip.append(node('div','tooltip-gsm',sample.gsm),node('div','tooltip-name',sample.name||sample.gsm));const fields=node('dl','tooltip-fields'),entries=[['Species',sample.organism||'Not specified']];const characteristics=(sample.characteristics||[]).map(value=>{const index=value.indexOf(':');return index>=0?[value.slice(0,index).trim(),value.slice(index+1).trim()]:['Details',value];});const tissue=characteristics.find(([key])=>/^(tissue|organ|tissue type)$/i.test(key));entries.push(['Tissue',tissue?.[1]||sample.source||'Not specified']);if(sample.source&&sample.source!==entries[1][1])entries.push(['Source',sample.source]);for(const [key,value] of characteristics){if(/^(tissue|organ|tissue type)$/i.test(key))continue;entries.push([key.charAt(0).toUpperCase()+key.slice(1),value]);}for(const [key,value] of entries)fields.append(node('dt','',key+':'),node('dd','',value));sampleTooltip.append(fields);document.body.append(sampleTooltip);positionSampleTooltip(event,row);}
  row.onmouseenter=show;row.onmousemove=event=>positionSampleTooltip(event,row);row.onmouseleave=hideSampleTooltip;item.onfocus=show;item.onblur=hideSampleTooltip;return row;
 }
}
async function refresh(force=false,preserveGroups=false){if(refreshing)return;refreshing=true;try{const s=await nzApi('state',{},true);if(pendingGroupWrites||resizingGroups||gseDrag)return;snapshot=s;if(typeof observeAutoAnalysis==='function')observeAutoAnalysis(s);const running=s.jobs.filter(j=>j.project_id===s.active_project&&['queued','running'].includes(j.status));$('status').textContent=route==='project'&&running.length?running.map(j=>j.phase).join(' · '):'';
 const p=s.project,name=route==='home'?'home':p?.stage==='analysis'?'analysis':'intake';showScreen(name);const processing=name==='intake'&&p?.stage==='processing';$('intake-loading').hidden=!processing;if(processing){hideSampleTooltip();if($('modal').open)$('modal').close();$('intake-loading-label').textContent=running.length?running.map(j=>j.phase||'Preparing analysis').join(' · '):'Preparing analysis…';}const key=name+':'+s.revision+':'+p?.id;if(force||key!==renderKey){if(name==='home')renderHome();else if(name==='intake'&&!(preserveGroups&&detailTab==='groups')&&(!processing||force||!renderKey.startsWith('intake:')||lastProject!==p.id))renderIntake();renderKey=key;}
 const viewer=$('viewer');viewer.hidden=name!=='analysis';if(name==='analysis'){$('panel-name').textContent='Uploaded panel: '+p.panel_name;$('direction').textContent='';if(force||lastProject!==p.id||!viewer.getAttribute('src')){setAnalysisLoading(true);viewer.src='/explorer.html?revision='+s.revision;dataRevision=p.data_revision;}else if((revision!==s.revision||dataRevision!==p.data_revision)&&!(dataRevision!==p.data_revision&&((typeof autoStarting!=='undefined'&&autoStarting)||running.some(j=>j.kind==='differential')))){viewer.contentWindow.postMessage({type:'workspace-update',revision:s.revision,force:dataRevision!==p.data_revision},location.origin);dataRevision=p.data_revision;}lastProject=p.id;}else if(name==='intake'){viewer.removeAttribute('src');lastProject=p.id;}revision=s.revision;
 }catch(e){$('status').textContent='Connection interrupted';console.error(e);}finally{refreshing=false;}}
window.addEventListener('message',e=>{if(e.origin===location.origin&&e.source===$('viewer').contentWindow&&e.data?.type==='workspace-saved')refresh();});
const brandToggle=$('brand-menu-toggle'),brandMenu=$('brand-menu');function closeBrandMenu(){brandMenu.hidden=true;brandToggle.setAttribute('aria-expanded','false');}brandToggle.onclick=()=>{brandMenu.hidden=!brandMenu.hidden;brandToggle.setAttribute('aria-expanded',String(!brandMenu.hidden));};document.addEventListener('click',e=>{if(!e.target.closest('.brand-menu-wrap'))closeBrandMenu();});document.addEventListener('keydown',e=>{if(e.key==='Escape')closeBrandMenu();});
async function showAIConnection(){
 closeBrandMenu();const box=node('div','ai-connection-dialog'),status=node('p','muted','Checking connection…'),actions=node('div','actions');
 box.append(node('h2','','AI connection'),status,node('p','muted','Restart Codex if NozeOmics is not listed yet.'));
 const connect=button('Connect to Codex',async()=>{status.textContent='Connecting…';try{display(await window.desktop.connectAI('connect'));}catch{status.textContent='Restart NozeOmics to enable connection setup.';}},'primary');
 const save=button('Save connection files',async()=>{const file=await window.desktop.saveConnection();await window.desktop.reveal(file);});
 function display(result){status.textContent=result.configured?'Codex configured':result.error||'Codex is not configured';}
 actions.append(save,connect);box.append(actions);$('modal-body').replaceChildren(box);$('modal').showModal();
 if(!window.desktop?.connectAI){status.textContent='Restart NozeOmics to enable connection setup.';connect.disabled=true;return;}
 try{display(await window.desktop.connectAI('status'));}catch{status.textContent='Could not check the connection. Please try again.';}
}
$('ai-connection').hidden=!window.desktop;$('ai-connection').onclick=()=>showAIConnection().catch(e=>toast(e.message));
if(window.desktop?.connectAI)window.desktop.connectAI('auto').then(result=>{if(result.changed)toast('AI connection configured. Restart Codex if needed.');else if(result.error)toast('AI connection could not be configured. Open AI connection to retry.');}).catch(()=>{});
let appActionRequest=null,appAction=null,appActionTimer=null,appActionFinishing=false;
async function finishAppAction(){if(appActionFinishing)return;appActionFinishing=true;clearTimeout(appActionTimer);const action=appAction;try{await Promise.race([groupQueue,new Promise(resolve=>setTimeout(resolve,1500))]);appActionRequest=null;appAction=null;if(action==='quit')await window.desktop.quit();else if(action==='home'){route='home';$('viewer').removeAttribute('src');lastProject=null;renderKey='';await refresh(true);}else location.reload();}finally{appActionFinishing=false;}}
function requestAppAction(action){if(appActionRequest||appActionFinishing)return;closeBrandMenu();appAction=action;const frame=$('viewer');if(frame.hidden||!frame.contentWindow){finishAppAction().catch(e=>toast(e.message));return;}appActionRequest=crypto.randomUUID();appActionTimer=setTimeout(()=>{if(action==='reload'||action==='quit'){finishAppAction().catch(e=>toast(e.message));}else{appActionRequest=null;appAction=null;toast('The viewer did not respond. Reload the app and try again.');}},4000);frame.contentWindow.postMessage({type:'prepare-app-reload',request:appActionRequest},location.origin);}
$('back-home').onclick=()=>requestAppAction('home');$('reload-app').onclick=()=>requestAppAction('reload');$('quit-app').hidden=!window.desktop;$('quit-app').onclick=()=>requestAppAction('quit');window.addEventListener('message',e=>{if(e.origin!==location.origin||e.source!==$('viewer').contentWindow||e.data?.request!==appActionRequest||!appActionRequest)return;if(e.data.type==='app-reload-ready')finishAppAction().catch(e=>toast(e.message));else if(e.data.type==='app-reload-failed'){clearTimeout(appActionTimer);if(appAction==='reload'||appAction==='quit'){finishAppAction().catch(e=>toast(e.message));}else{appActionRequest=null;appAction=null;toast('Could not save your latest changes. Please try again.');}}});
let desktopReadySent=false;async function refreshDesktop(){await refresh();if(snapshot&&!desktopReadySent&&window.desktop?.ready){desktopReadySent=true;window.desktop.ready().catch(()=>{});}}refreshDesktop();setInterval(refreshDesktop,1500);

function setAnalysisLoading(loading){if(!loading&&window.analysisPCALoading)return;if(!loading&&typeof keepRecalculationLoading==='function'&&keepRecalculationLoading())return;$('analysis-loading').hidden=!loading;}
window.addEventListener('message',e=>{if(e.origin!==location.origin||e.source!==$('viewer').contentWindow)return;if(e.data?.type==='viewer-loading')setAnalysisLoading(true);if(e.data?.type==='viewer-ready'){window.analysisViewerReady=true;window.analysisLoadedDataRevision=e.data.dataRevision;setAnalysisLoading(typeof autoStarting!=='undefined'&&(autoStarting||(snapshot?.jobs||[]).some(j=>j.project_id===snapshot?.project?.id&&j.kind==='differential'&&['queued','running'].includes(j.status))));}});

window.addEventListener('message',e=>{if(e.origin!==location.origin||e.source!==$('viewer').contentWindow)return;if(e.data?.type==='pca-loading'){window.analysisPCALoading=e.data.key;window.analysisPCAStarted=Date.now();setAnalysisLoading(true);}else if(e.data?.type==='pca-ready'&&window.analysisPCALoading===e.data.key){window.analysisPCALoading=null;setAnalysisLoading(false);}});

window.addEventListener('message',e=>{if(e.origin!==location.origin||e.source!==$('viewer').contentWindow||e.data?.type!=='graph-controls')return;const graph=e.data.graph;$('graph-controls').dataset.graph=graph;$('graph-controls').hidden=$('analysis').hidden||!['trend','ma','heatmap','pca'].includes(graph);$('graph-add').hidden=graph!=='ma';});

if(document.getElementById("app-version"))document.getElementById("app-version").textContent="Version "+(NOZEOMICS.version||"0.2.0");
