import {createRequire} from 'node:module';import {pathToFileURL,fileURLToPath} from 'node:url';import path from 'node:path';import fs from 'node:fs';import assert from 'node:assert/strict';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');const deps='C:/Users/nojae/OneDrive/Desktop/노제/NozeDock v3/frontend';const require=createRequire(path.join(deps,'package.json'));
const {Client}=await import(pathToFileURL(require.resolve('@modelcontextprotocol/sdk/client/index.js')));const {StdioClientTransport}=await import(pathToFileURL(require.resolve('@modelcontextprotocol/sdk/client/stdio.js')));
const home=path.join(root,'.local','packaged-check'),exe=path.join(root,'release/NozeOmics-win32-x64/NozeOmics.exe'),adapter=path.join(root,'release/NozeOmics-win32-x64/resources/app/mcp/adapter.cjs');
const env={...process.env,NOZEOMICS_HOME:home,ELECTRON_RUN_AS_NODE:'1',NOZEOMICS_EXE:exe};
const clients=[];async function create(){const c=new Client({name:'acceptance-test',version:'1'},{capabilities:{}});await c.connect(new StdioClientTransport({command:exe,args:[adapter],env}));clients.push(c);return c;}
const runId=String(Date.now());
async function call(c,name,args={}){if(args.request_id)args={...args,request_id:runId+'-'+args.request_id};const result=await c.callTool({name:'nozeomics_'+name,arguments:args});return {value:JSON.parse(result.content[0].text),error:!!result.isError};}
try{const a=await create(),b=await create();assert.equal((await a.listTools()).tools.length,16);let s=(await call(a,'get_state')).value;assert.ok(s.revision>=0);
 await call(a,'open_project',{name:'MCP integration acceptance',base_revision:s.revision});s=(await call(b,'get_state')).value;assert.equal(s.project.name,'MCP integration acceptance');const old=s.revision;
 let r=await call(b,'update_view',{panel:['G1','G2'],base_revision:old,request_id:'mcp-panel-1'});assert.equal(r.error,false);r=await call(a,'update_view',{panel:['G3'],base_revision:old,request_id:'mcp-stale-1'});assert.equal(r.value.error.code,'revision_conflict');
 const stage=(await call(a,'prepare_import')).value;fs.mkdirSync(stage.staging_path,{recursive:true});const file=path.join(stage.staging_path,'counts.tsv');const columns=Array.from({length:8},(_,i)=>'S'+i);let text='gene\t'+columns.join('\t')+'\n';for(let g=0;g<120;g++){const values=columns.map((_,i)=>Math.round((100+g*4+(g*i*13)%97)*(g<10&&i>=4?4:1)));text+='G'+g+'\t'+values.join('\t')+'\n';}fs.writeFileSync(file,text);
 const samples=columns.map((id,i)=>({id,source_column:id,subject:String(i%4),tissue:'liver',biological_replicate:true,evidence:[{source:file,locator:'header '+id,value:id}]}));s=(await call(a,'get_state')).value;
 r=await call(a,'import_dataset',{path:file,organism:'mouse',recipe:{gene_column:'gene',unit:'raw_count',identifiers:'symbol'},samples,base_revision:s.revision});assert.equal(r.error,false,JSON.stringify(r));const did=r.value.dataset.id;
 s=(await call(a,'get_state')).value;r=await call(a,'configure_comparison',{dataset_id:did,groups:Object.fromEntries(columns.map((id,i)=>[id,i<4?'Group A':'Group B'])),blocking_fields:['subject'],label:'Paired MCP test',base_revision:s.revision});assert.equal(r.error,false);const cid=r.value.comparison.id;
 for(const kind of ['differential','pca']){s=(await call(a,'get_state')).value;r=await call(a,'start_analysis',{comparison_id:cid,kind,base_revision:s.revision,request_id:'mcp-'+kind});assert.equal(r.error,false);let job;for(let i=0;i<100;i++){job=(await call(b,'get_job',{job_id:r.value.job.id})).value;if(!['running','queued'].includes(job.status))break;await new Promise(r=>setTimeout(r,150));}assert.equal(job.status,'completed',JSON.stringify(job));assert.equal(job.applied,true);}
 s=(await call(b,'get_state')).value;r=await call(b,'update_view',{view:{graphType:'pca',maDatasetId:cid},base_revision:s.revision,request_id:'mcp-pca-view'});assert.equal(r.error,false);
 let receipt;for(let i=0;i<50;i++){s=(await call(a,'get_state')).value;receipt=s.viewer_receipts.find(v=>v.plot==='pca'&&v.revision>=r.value.revision);if(receipt)break;await new Promise(r=>setTimeout(r,150));}assert.ok(receipt,'Actual Electron viewer did not acknowledge the current PCA revision');
 r=await call(a,'export_project',{kind:'bundle'});assert.ok(fs.existsSync(r.value.path));console.log('PASS: packaged executable, two SDK clients, shared state, revision conflict, paired analysis, PCA, actual viewer receipt, bundle export.');
}finally{await Promise.all(clients.map(c=>c.close()));}
