import {createRequire} from 'node:module';
import {pathToFileURL,fileURLToPath} from 'node:url';
import path from 'node:path';import fs from 'node:fs';import {spawn,spawnSync} from 'node:child_process';import assert from 'node:assert/strict';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const require=createRequire('C:/Users/nojae/OneDrive/Desktop/노제/NozeDock v3/frontend/package.json');
const {Client}=await import(pathToFileURL(require.resolve('@modelcontextprotocol/sdk/client/index.js')));
const {StdioClientTransport}=await import(pathToFileURL(require.resolve('@modelcontextprotocol/sdk/client/stdio.js')));
const home=path.join(root,'.local','intake-ui-'+Date.now()),exe=path.join(root,'release/NozeOmics-win32-x64/NozeOmics.exe');
const seed=spawnSync(path.join(root,'runtime/python/python.exe'),[path.join(root,'tests/seed_intake_ui.py'),home],{cwd:root,windowsHide:true,encoding:'utf8'});assert.equal(seed.status,0,seed.stderr);
const env={...process.env,NOZEOMICS_HOME:home,CODEX_HOME:path.join(home,'isolated-codex')};delete env.ELECTRON_RUN_AS_NODE;
const port=9368,app=spawn(exe,['--remote-debugging-address=127.0.0.1','--remote-debugging-port='+port],{env,windowsHide:true,stdio:'ignore'});
let socket,client;const pending=new Map();let sequence=0;const delay=ms=>new Promise(r=>setTimeout(r,ms));
async function until(fn){for(let i=0;i<200;i++){try{const v=await fn();if(v)return v;}catch{}await delay(100);}throw new Error('Desktop integration timed out.');}
function rpc(method,params={}){const id=++sequence;return new Promise((resolve,reject)=>{const timeout=setTimeout(()=>{pending.delete(id);reject(new Error('Timed out: '+method));},20000);pending.set(id,{resolve:v=>{clearTimeout(timeout);resolve(v);},reject:e=>{clearTimeout(timeout);reject(e);}});socket.send(JSON.stringify({id,method,params}));});}
async function evaluate(expression){const r=await rpc('Runtime.evaluate',{expression,returnByValue:true,awaitPromise:true});if(r.exceptionDetails)throw new Error(JSON.stringify(r.exceptionDetails));return r.result.value;}
async function call(name,args={}){const r=await client.callTool({name:'nozeomics_'+name,arguments:args});const v=JSON.parse(r.content[0].text);if(r.isError)throw new Error(JSON.stringify(v));return v;}
async function shot(name){const r=await rpc('Page.captureScreenshot',{format:'png'});fs.writeFileSync(path.join(root,'.local',name+'.png'),Buffer.from(r.data,'base64'));}
try{
 const c=await until(()=>JSON.parse(fs.readFileSync(path.join(home,'connection.json'),'utf8')));
 const target=await until(async()=>{const list=await (await fetch('http://127.0.0.1:'+port+'/json/list')).json();return list.find(t=>t.type==='page'&&t.url.startsWith(c.url));});
 socket=new WebSocket(target.webSocketDebuggerUrl);await new Promise((resolve,reject)=>{socket.addEventListener('open',resolve,{once:true});socket.addEventListener('error',reject,{once:true});});socket.addEventListener('message',e=>{const r=JSON.parse(e.data),p=pending.get(r.id);if(p){pending.delete(r.id);r.error?p.reject(new Error(r.error.message)):p.resolve(r.result);}});
 await until(()=>evaluate('document.querySelectorAll(".project-card").length===2'));
 assert.equal(await evaluate('document.getElementById("home").hidden'),false);
 assert.equal(await evaluate('document.querySelector("nav")===null'),true);
 assert.equal(await evaluate('document.documentElement.scrollHeight<=innerHeight'),true);
 await shot('intake-projects');
 await evaluate('document.querySelectorAll(".project-card")[1].click();true');
 await until(()=>evaluate('!document.getElementById("intake").hidden && document.querySelectorAll(".gse-bookmarks button").length===6'));
 const positions=await evaluate('[...document.querySelectorAll(".gse-card-main")].map(el=>{const r=el.getBoundingClientRect();return {x:r.left+35,y:r.top+r.height/2,bottom:r.bottom};})');
 await rpc('Input.dispatchMouseEvent',{type:'mouseMoved',x:positions[0].x,y:positions[0].y});
 await rpc('Input.dispatchMouseEvent',{type:'mousePressed',x:positions[0].x,y:positions[0].y,button:'left',buttons:1,clickCount:1});
 await rpc('Input.dispatchMouseEvent',{type:'mouseMoved',x:positions[0].x,y:positions[0].y+12,button:'left',buttons:1});
 await rpc('Input.dispatchMouseEvent',{type:'mouseMoved',x:positions[1].x,y:positions[1].bottom-3,button:'left',buttons:1});
 await rpc('Input.dispatchMouseEvent',{type:'mouseReleased',x:positions[1].x,y:positions[1].bottom-3,button:'left',buttons:0,clickCount:1});
 await until(()=>evaluate('snapshot.project.intake_order?.[0]==="ui-second"'));
 assert.equal(await evaluate('document.querySelector(".gse-card").dataset.entry'),'ui-second');
 await evaluate('refresh(true).then(()=>true)');
 assert.equal(await evaluate('document.querySelector(".gse-card").dataset.entry'),'ui-second');
 await evaluate('document.querySelector("[data-entry=ui-second] .gse-remove").click();true');
 await evaluate('document.querySelector("#modal .actions button.primary").click();true');
 await until(()=>evaluate('document.querySelectorAll(".gse-card").length===1'));
 await evaluate('document.querySelector(".gse-remove").click();true');
 assert.equal(await evaluate('document.getElementById("modal").open'),true);
 await evaluate('document.querySelector("#modal .actions button").click();true');
 await evaluate('document.getElementById("intake-complete").click();true');
 await until(()=>evaluate('document.getElementById("modal").open'));
 assert.equal(await evaluate('snapshot.project.stage'), 'intake');
 await evaluate('document.querySelector("#modal .actions button").click();true');
 await evaluate('document.querySelectorAll(".gse-bookmarks button")[1].click();true');
 await until(()=>evaluate('document.querySelectorAll(".included-section .sample-item").length===4'));
 assert.equal(await evaluate('document.querySelectorAll("#gse-detail select").length'),1);
 const split=await evaluate('({top:document.querySelector(".included-section").getBoundingClientRect().height,bottom:document.querySelector(".available-section").getBoundingClientRect().height})');
 assert.ok(split.bottom/split.top>1.8&&split.bottom/split.top<2.2);
 await evaluate('document.querySelector(".group-divider").dispatchEvent(new KeyboardEvent("keydown",{key:"ArrowDown"}));true');
 assert.ok(await evaluate('groupViews.get("ui-entry").ratio>1/3'));
 await evaluate('document.querySelector(".group-divider").dispatchEvent(new KeyboardEvent("keydown",{key:"Home"}));true');
 await evaluate('window.rapidToggle=document.querySelector(".sample-group-toggle");for(let i=0;i<11;i++)rapidToggle.click();true');
 assert.equal(await evaluate('rapidToggle.textContent'), 'Treated');
 await evaluate('groupQueue.then(()=>true)');
 assert.equal(await evaluate('rapidToggle.isConnected'),true);
 assert.equal(await evaluate('snapshot.project.intake["ui-entry"].groups.GSM0'), 'Group B');
 await evaluate('rapidToggle.click();groupQueue.then(()=>true)');

 await evaluate('document.querySelector(".compact-sample").dispatchEvent(new MouseEvent("mouseenter"));true');
 assert.equal(await evaluate('document.querySelector(".sample-tooltip").textContent.includes("Treatment:")'),true);
 await evaluate('document.querySelector(".compact-sample").dispatchEvent(new MouseEvent("mousemove",{clientX:500,clientY:180}));true');
 assert.deepEqual(await evaluate('({x:parseFloat(sampleTooltip.style.left),y:parseFloat(sampleTooltip.style.top)})'),{x:516,y:196});
 await evaluate('document.querySelector(".compact-sample").dispatchEvent(new MouseEvent("mousemove",{clientX:innerWidth-20,clientY:180}));true');
 assert.ok(await evaluate('sampleTooltip.getBoundingClientRect().right<innerWidth-20'));
 await evaluate('window.preparationCard=document.querySelector(".gse-card");window.actualApi=nzApi;nzApi=async(...args)=>{const s=await actualApi(...args);if(args[0]==="state"){s.project.stage="processing";}return s;};refresh(true).then(()=>true)');
 assert.equal(await evaluate('document.getElementById("intake").hidden'),false);
 assert.equal(await evaluate('document.getElementById("intake-loading").hidden'),false);
 assert.equal(await evaluate('document.getElementById("viewer").hasAttribute("src")'),false);
 await evaluate('refresh().then(()=>true)');
 assert.equal(await evaluate('window.processingCard=document.querySelector(".gse-card");refresh().then(()=>processingCard===document.querySelector(".gse-card"))'),true);
 await evaluate('nzApi=actualApi;refresh(true).then(()=>true)');
 assert.equal(await evaluate('document.getElementById("intake-loading").hidden'),true);
 await evaluate('document.querySelector(".included-section .sample-item").click();true');
 await until(()=>evaluate('snapshot.project.intake["ui-entry"].groups.GSM0==="N/A"'));
 await evaluate('document.querySelector(".available-section .sample-item").click();true');
 await until(()=>evaluate('snapshot.project.intake["ui-entry"].groups.GSM0==="Group A"'));
 await evaluate('document.querySelector(".sample-group-toggle").click();true');
 await until(()=>evaluate('snapshot.project.intake["ui-entry"].groups.GSM0==="Group B"'));
 await evaluate('document.querySelector(".included-section .sample-item").click();true');
 await until(()=>evaluate('document.querySelector(".available-section .sample-item")!==null'));
 await evaluate('const filter=document.querySelector("#gse-detail select");filter.value="treated";filter.dispatchEvent(new Event("change"));true');
 assert.equal(await evaluate('document.querySelectorAll(".available-section .sample-item").length'),0);
 assert.ok(await evaluate('document.querySelector(".available-section .picker-heading").textContent.includes("0 / 1 samples")'));
 await evaluate('document.querySelector("#gse-detail select").value="";document.querySelector("#gse-detail select").dispatchEvent(new Event("change"));document.querySelector(".available-section .sample-item").click();true');
 await until(()=>evaluate('snapshot.project.intake["ui-entry"].groups.GSM0==="Group A"'));
 await evaluate('document.querySelector(".sample-group-toggle").click();true');
 await until(()=>evaluate('snapshot.project.intake["ui-entry"].groups.GSM0==="Group B"'));
 assert.equal(await evaluate('document.documentElement.scrollHeight<=innerHeight'),true);
 await shot('intake-groups');
 client=new Client({name:'intake-ui-check',version:'1'},{capabilities:{}});
 await client.connect(new StdioClientTransport({command:exe,args:[path.join(path.dirname(exe),'resources/app/mcp/adapter.cjs')],env:{...env,ELECTRON_RUN_AS_NODE:'1',NOZEOMICS_EXE:exe}}));
 assert.ok((await client.listTools()).tools.some(t=>t.name==='nozeomics_review_intake'));
 const denied=await fetch(c.url+'/api/review_intake',{method:'POST',headers:{Authorization:'Bearer '+c.token,'Content-Type':'application/json'},body:'{}'});assert.equal(denied.status,400);assert.equal((await denied.json()).error.code,'ai_review_required');
 let s=await call('get_state');const pid=s.active_project,e=(await call('get_intake')).entries[0];
 const registered=await call('import_results',{path:e.files[0].path,organism:'human',gse:e.gse,recipe:{data_type:'filtered_de',gene_column:'gene',effect_column:'logFC',effect_scale:'log2',direction:'B_vs_A',identifiers:'symbol',p_column:'p',adjusted_p_column:'padj',average_column:'AveExpr',average_scale:'log2'}});
 s=await call('get_state');
 await call('review_intake',{project_id:pid,base_revision:s.revision,decisions:[{entry_id:e.id,review_fingerprint:e.review_fingerprint,verdict:'approve',note:'Verified submitted results and treatment direction.',dataset_ids:[registered.dataset_id],contrast_evidence:'Study source describes B vs A.'}]});
 await until(()=>evaluate('!document.getElementById("analysis").hidden && document.getElementById("viewer").contentDocument?.querySelector("#nz-graph-heatmap")?.disabled'));
 assert.equal(await evaluate('document.getElementById("viewer").contentDocument.querySelector("#nz-graph-pca").disabled'),true);
 assert.equal(await evaluate('document.getElementById("viewer").contentDocument.querySelectorAll("#nz-graph svg circle").length>=2'),true);

 const controls=await evaluate('[...document.getElementById("viewer").contentDocument.querySelectorAll(".nz-graph-option")].map(b=>b.id)');
 assert.deepEqual(controls,['nz-graph-pca','nz-graph-ma','nz-graph-trend','nz-graph-heatmap','nz-graph-pathway']);
 const oldMode=await evaluate('document.getElementById("viewer").contentDocument.getElementById("nz-show-type-select").value');
 const fixedAxis=await evaluate('document.getElementById("viewer").contentDocument.getElementById("nz-y-axis").textContent.split("Log2")[0]');
 await evaluate('document.getElementById("viewer").contentDocument.getElementById("nz-graph-trend").click();true');
 assert.notEqual(await evaluate('document.getElementById("viewer").contentDocument.getElementById("nz-show-type-select").value'),oldMode);
 assert.equal(await evaluate('document.getElementById("viewer").contentDocument.getElementById("nz-y-axis").textContent.split("Log2")[0]'),fixedAxis);
 await evaluate('document.getElementById("viewer").contentDocument.querySelector("[data-show-type=mean]").click();true');
 assert.equal(await evaluate('document.getElementById("viewer").contentDocument.getElementById("nz-show-type-select").value'),'mean');
 await evaluate('document.getElementById("viewer").contentDocument.getElementById("nz-graph-pathway").click();true');
 assert.equal(await evaluate('getComputedStyle(document.getElementById("viewer").contentDocument.getElementById("nz-pathway-view")).display'),'flex');
 assert.equal(await evaluate('document.getElementById("viewer").contentDocument.getElementById("nz-trend-bookmarks").hidden'),false);
 await evaluate('document.getElementById("viewer").contentDocument.getElementById("nz-toggle-left").click();document.getElementById("viewer").contentDocument.getElementById("nz-toggle-right").click();true');
 assert.equal(await evaluate('getComputedStyle(document.getElementById("viewer").contentDocument.querySelector(".nz-side")).display'),'none');
 assert.equal(await evaluate('getComputedStyle(document.getElementById("viewer").contentDocument.querySelector(".nz-gene-side")).display'),'none');
 await evaluate('document.getElementById("viewer").contentDocument.getElementById("nz-toggle-left").click();document.getElementById("viewer").contentDocument.getElementById("nz-toggle-right").click();true');
 await rpc('Emulation.setDeviceMetricsOverride',{width:800,height:600,deviceScaleFactor:1,mobile:false});
 assert.equal(await evaluate('[...document.getElementById("viewer").contentDocument.querySelectorAll(".nz-graph-option svg")].every(svg=>svg.getBoundingClientRect().right<=svg.parentElement.getBoundingClientRect().right)'),true);
 await shot('analysis-compact-controls');
 await rpc('Emulation.clearDeviceMetricsOverride');
 await evaluate('document.getElementById("viewer").contentDocument.getElementById("nz-graph-ma").click();true');
 await until(()=>evaluate('document.getElementById("viewer").contentDocument.getElementById("nz-ma-status").textContent.includes("2 genes")'));
 assert.equal(await evaluate('document.getElementById("viewer").contentDocument.getElementById("nz-ma-gene-search").nextElementSibling.classList.contains("nz-right-significance")'), true);
 await shot('intake-analysis');
 await evaluate('window.__reloadProbe=true;document.getElementById("viewer").src="about:blank";true');
 await new Promise(resolve=>setTimeout(resolve,100));
 await evaluate('document.getElementById("reload-app").click();true');
 await until(()=>evaluate('window.__reloadProbe===undefined && !!snapshot'));

 await evaluate('document.getElementById("back-home").click();true');
 await until(()=>evaluate('!document.getElementById("home").hidden'));
 await evaluate('document.getElementById("new").click();true');
 await until(()=>evaluate('document.getElementById("modal").open'));
 await evaluate('document.querySelector("#modal input").value="New empty study";document.querySelector("#modal .actions button").click();true');
 await until(()=>evaluate('snapshot.project?.name==="New empty study" && !document.getElementById("intake").hidden'));
 assert.equal(await evaluate('document.getElementById("gse-detail").textContent.trim()===""'),true);
 console.log('PASS: Projects → intake, saved groups, MCP-only review, automatic Analysis, result-only Trend/MA with disabled Heatmap/PCA, back navigation, New project and viewport containment.');
}finally{
 socket?.close();await client?.close();if(app.exitCode===null)spawn(exe,['--quit'],{env,windowsHide:true,stdio:'ignore'});
}
