import {Server} from '@modelcontextprotocol/sdk/server/index.js';
import {StdioServerTransport} from '@modelcontextprotocol/sdk/server/stdio.js';
import {CallToolRequestSchema,ListToolsRequestSchema} from '@modelcontextprotocol/sdk/types.js';
import fs from 'node:fs';import path from 'node:path';import {spawn} from 'node:child_process';
import storage from '../desktop/workspace-home.cjs';
import releaseInfo from '../release.json' with {type:'json'};
const home=storage.workspaceHome();
const schema=(properties={},required=[])=>({type:'object',properties,required,additionalProperties:false});const str={type:'string'},integer={type:'integer'},obj={type:'object'},strings={type:'array',items:str},revision={base_revision:integer,request_id:str};
const tools=[
 ['get_state','Read the shared project, revision, comparisons, gene panel, view, jobs and viewer receipts.',schema()],
 ['open_project','Open an existing project or create one. Use workflow:intake for new GEO batches; legacy direct imports remain supported.',schema({name:str,project_id:str,workflow:{enum:['intake','direct']},base_revision:integer})],
 ['add_gses','Add multiple GSEs to the intake screen. Only GEO reports, GSM metadata and file inventory are retrieved; no source files are downloaded. Returns immediately.',schema({accessions:strings,project_id:str,base_revision:integer},['accessions'])],
 ['select_intake_files','After reviewing metadata, choose only necessary source file IDs with a rationale. Downloads run asynchronously and reuse verified caches. Read get_intake for completion before inspecting sources.',schema({entry_id:str,file_ids:strings,note:str,project_id:str,base_revision:integer},['entry_id','file_ids','note','project_id'])],
 ['get_intake','Read pending GSEs, user GSM group assignments, local metadata/source paths, file hashes, review fingerprints and cached approvals. Inspect actual files before review; never infer expression units from filenames alone.',schema({entry_id:str,offset:integer,limit:integer})],
 ['update_intake','Set GSM Group A/Group B/N/A assignments, retry retrieval, or exclude a GSE. Changes invalidate its AI approval; other approved GSEs remain cached.',schema({entry_id:str,groups:obj,action:{enum:['retry','exclude','reorder']},order:strings,project_id:str,base_revision:integer},['entry_id'])],
 ['review_intake','After inspecting sources, importing verified data and configuring comparisons, record batch decisions [{entry_id,review_fingerprint,verdict:approve/return,note,dataset_ids,source_limitations?,contrast_evidence?}]. Read get_intake freshly. Submitted result tables need contrast_evidence confirming Control/Treated and B-vs-A direction. Approval schedules analysis and automatically opens Analysis only when every retained GSE is approved and processing succeeds.',schema({decisions:{type:'array',items:obj},project_id:str,base_revision:integer},['decisions','project_id','base_revision'])],
 ['import_results','Register submitted DE results without inventing sample expression. recipe: data_type de_result/filtered_de; gene_column; effect_column; effect_scale log2; direction B_vs_A/A_vs_B; optional average_column, average_scale log2/log10/linear (linear needs average_offset), p_column, adjusted_p_column, identifiers symbol or symbol_column. Result-only data supports Trend and MA if average exists; not sample Heatmap/PCA/recalculation.',schema({path:str,organism:str,gse:str,recipe:obj,label:str,a_label:str,b_label:str,tissue:str,base_revision:integer},['path','organism','gse','recipe'])],
 ['prepare_import','Get a project staging directory and callable bundled Python interpreter for an explicit adapter.',schema()],
 ['inspect_source','Inspect a matrix header/first rows or fetch GEO metadata. Full metadata is saved locally; sample preview is paginated with offset/limit (default 20).',schema({path:str,gse:str,offset:integer,limit:integer})],
 ['fetch_source','Download an HTTPS NCBI/EBI source to this project; large files may take time.',schema({url:str,filename:str},['url'])],
 ['import_dataset','Register an explicit genes-by-samples matrix or legacy Cell 4 workbook. recipe: unit, gene_column, identifiers/symbol_column, header, separator, row_names, annotate. Each sample needs id/gsm, source_column, evidence[{source,locator,value}], and available tissue/subject/batch metadata. No automatic guessed A/B matching.',schema({path:str,organism:str,gse:str,tissue:str,recipe:obj,samples:{type:'array',items:obj},label:str,legacy:{type:'boolean'},adapter_path:str,base_revision:integer},['path'])],
 ['configure_comparison','Create a same-tissue comparison. groups maps sample IDs to Group A/Group B/N/A. Direction B vs A. Paired designs use blocking_fields:[subject].',schema({dataset_id:str,groups:obj,label:str,a_label:str,b_label:str,blocking_fields:strings,base_revision:integer},['dataset_id','groups'])],
 ['update_view','Change the same viewer state/panel as the user. Stable comparison IDs key selected_samples, modes and collapsed; dataset_selected_samples is for PCA without a contrast; hiddenGenes uses names. graphType trend/ma/heatmap/pca, maDatasetId, maSearchName, maViewport, cutoffIndex, significanceMetric adj_p/p_value. Always use a freshly read base_revision.',schema({view:obj,panel:strings,panel_name:str,project_id:str,...revision})],
 ['start_analysis','Queue differential or pca; returns job ID immediately. Uses original assay and the current comparison design. PCA n_top=500/1000/2000/0; can run on dataset_id without a comparison.',schema({comparison_id:str,dataset_id:str,kind:{enum:['differential','pca']},n_top:{enum:[0,500,1000,2000]},...revision})],
 ['get_job','Read job status, errors and saved run path; completion does not imply current viewer applied the result.',schema({job_id:str},['job_id'])],
 ['control_job','Explicitly cancel a running job.',schema({job_id:str,action:{enum:['cancel']}},['job_id'])],
 ['get_evidence','Read original hash, transformation recipe, annotation source and verified sample mappings.',schema({dataset_id:str,sample_id:str},['dataset_id'])],
 ['inspect_dataset','Read compact feature/sample metadata and requested feature values. Does not return an entire matrix.',schema({dataset_id:str,feature_ids:strings,offset:integer,limit:integer},['dataset_id'])],
 ['export_project','Save current results, panel, template, summary or source-inclusive project bundle.',schema({kind:{enum:['results','panel','template','summary','bundle']},comparison_id:str,filename:str})],
 ['restore_project','Open a saved .nozeomics.zip project bundle.',schema({path:str,base_revision:integer},['path'])],
 ['import_panel','Load a gene panel workbook/text file into the shared UI.',schema({path:str,base_revision:integer},['path'])]
].map(([name,description,inputSchema])=>({name:'nozeomics_'+name,description,inputSchema}));
async function connection(){for(let i=0;i<200;i++){try{const c=JSON.parse(fs.readFileSync(path.join(home,'connection.json'),'utf8'));const r=await fetch(c.url+'/health',{signal:AbortSignal.timeout(1000)});if(r.ok)return c;}catch{}if(i===0){const exe=process.env.NOZEOMICS_EXE;if(exe&&fs.existsSync(exe)){const env={...process.env};delete env.ELECTRON_RUN_AS_NODE;spawn(exe,['--background'],{env,detached:true,windowsHide:true,stdio:'ignore'}).unref();}else throw new Error('Open NozeOmics before connecting the AI.');}await new Promise(r=>setTimeout(r,100));}throw new Error('NozeOmics did not become ready. Open the program and inspect its service log.');}
const server=new Server({name:'nozeomics',version:releaseInfo.version},{capabilities:{tools:{}}});server.setRequestHandler(ListToolsRequestSchema,async()=>({tools}));
server.setRequestHandler(CallToolRequestSchema,async request=>{try{const tool=tools.find(t=>t.name===request.params.name);if(!tool)throw new Error('Unknown NozeOmics tool');const method=tool.name.replace('nozeomics_','');const c=await connection();const read=method==='get_state';const headers={Authorization:'Bearer '+c.token,'Content-Type':'application/json'};if(['review_intake','select_intake_files'].includes(method))headers['X-NozeOmics-Reviewer']=c.reviewer_token||'';const response=await fetch(c.url+'/api/'+(read?'state':method),{method:read?'GET':'POST',headers,body:read?undefined:JSON.stringify(request.params.arguments||{})});const result=await response.json();return {content:[{type:'text',text:JSON.stringify(result)}],isError:!response.ok};}catch(e){return {content:[{type:'text',text:JSON.stringify({error:{code:'connection_error',message:e.message}})}],isError:true};}});
tools.find(t=>t.name==='nozeomics_import_dataset').inputSchema.properties.study_info=obj;
server.connect(new StdioServerTransport()).catch(error=>{process.stderr.write(error.message+'\n');process.exitCode=1;});
