import {createRequire} from 'node:module';import {fileURLToPath} from 'node:url';import path from 'node:path';import fs from 'node:fs/promises';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');const deps=process.env.NOZEOMICS_BUILD_DEPS||'C:/Users/nojae/OneDrive/Desktop/노제/NozeDock v3/frontend/node_modules';const require=createRequire(path.join(deps,'../package.json'));const {packager}=require('@electron/packager');const electron=require('electron/package.json');
const releaseConfig=JSON.parse(await fs.readFile(path.join(root,'release.json'),'utf8'));
await import('./build.mjs');const stage=path.join(root,'.build/stage');await fs.mkdir(stage,{recursive:true});
for(const name of ['backend','frontend','desktop','mcp','assets','runtime','plugin','package.json','release.json'])await fs.cp(path.join(root,name),path.join(stage,name),{recursive:true,filter:p=>!p.includes('__pycache__')&&!p.endsWith('.pyc')&&!p.endsWith('-win.exe')&&!p.endsWith('.zip')&&!p.includes('reference-noze')&&!p.endsWith('adapter.mjs')});
// Python's standard-library ZIP is a runtime dependency.
await fs.copyFile(path.join(root,'runtime/python/python312.zip'),path.join(stage,'runtime/python/python312.zip'));
const out=path.join(root,'release');const packages=await packager({dir:stage,name:'NozeOmics',executableName:'NozeOmics',platform:'win32',arch:'x64',electronVersion:electron.version,electronZipDir:path.join(root,'.build/electron-cache'),out,overwrite:true,asar:false,prune:false,icon:path.join(root,'assets/Omics.ico'),appVersion:releaseConfig.version,appCopyright:'NozeOmics',win32metadata:{ProductName:'NozeOmics',FileDescription:'NozeOmics local expression analysis workspace'}});
for(const p of packages){await fs.copyFile(path.join(root,'README.md'),path.join(p,'START HERE.md'));await fs.cp(path.join(root,'docs'),path.join(p,'docs'),{recursive:true});await fs.copyFile(path.join(root,'requirements.txt'),path.join(p,'requirements.txt'));await fs.mkdir(path.join(p,'examples'),{recursive:true});for(const file of await fs.readdir(path.join(root,'fixtures')))if(file.endsWith('.nozeomics.zip'))await fs.copyFile(path.join(root,'fixtures',file),path.join(p,'examples',file));console.log(p);}
